In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

df = pd.read_csv("C:\\Users\\Asus\\OneDrive\\Desktop\\Explainable-Credit-Risk-System\\data\\raw\\application_train.csv")

print(df.shape)

(307511, 122)

In [2]:
df = df[df["CODE_GENDER"] != "XNA"]

print(df.shape)

(307507, 122)

In [3]:
df["DAYS_EMPLOYED"] = df["DAYS_EMPLOYED"].replace(
    365243,
    np.nan
)

In [4]:
(df["DAYS_EMPLOYED"] == 365243).sum()

np.int64(0)

In [5]:
missing_percent = (
    df.isnull().sum() / len(df) * 100
)

missing_percent = missing_percent.sort_values(
    ascending=False
)

missing_percent.head(20)

COMMONAREA_AVG              69.872231
COMMONAREA_MODE             69.872231
COMMONAREA_MEDI             69.872231
NONLIVINGAPARTMENTS_MEDI    69.433216
NONLIVINGAPARTMENTS_MODE    69.433216
NONLIVINGAPARTMENTS_AVG     69.433216
FONDKAPREMONT_MODE          68.386411
LIVINGAPARTMENTS_AVG        68.355192
LIVINGAPARTMENTS_MEDI       68.355192
LIVINGAPARTMENTS_MODE       68.355192
FLOORSMIN_MODE              67.848862
FLOORSMIN_AVG               67.848862
FLOORSMIN_MEDI              67.848862
YEARS_BUILD_AVG             66.497998
YEARS_BUILD_MODE            66.497998
YEARS_BUILD_MEDI            66.497998
OWN_CAR_AGE                 65.991018
LANDAREA_MEDI               59.376860
LANDAREA_AVG                59.376860
LANDAREA_MODE               59.376860
dtype: float64

In [6]:
high_missing_cols = missing_percent[
    missing_percent > 65
].index.tolist()

print("Columns to Drop:")
print(high_missing_cols)

print("\nCount:")
print(len(high_missing_cols))

Columns to Drop:
['COMMONAREA_AVG', 'COMMONAREA_MODE', 'COMMONAREA_MEDI', 'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAPARTMENTS_AVG', 'FONDKAPREMONT_MODE', 'LIVINGAPARTMENTS_AVG', 'LIVINGAPARTMENTS_MEDI', 'LIVINGAPARTMENTS_MODE', 'FLOORSMIN_MODE', 'FLOORSMIN_AVG', 'FLOORSMIN_MEDI', 'YEARS_BUILD_AVG', 'YEARS_BUILD_MODE', 'YEARS_BUILD_MEDI', 'OWN_CAR_AGE']

Count:
17

In [7]:
cols_to_drop = [
    'COMMONAREA_AVG',
    'COMMONAREA_MODE',
    'COMMONAREA_MEDI',
    'NONLIVINGAPARTMENTS_MEDI',
    'NONLIVINGAPARTMENTS_MODE',
    'NONLIVINGAPARTMENTS_AVG',
    'FONDKAPREMONT_MODE',
    'LIVINGAPARTMENTS_AVG',
    'LIVINGAPARTMENTS_MEDI',
    'LIVINGAPARTMENTS_MODE',
    'FLOORSMIN_MODE',
    'FLOORSMIN_AVG',
    'FLOORSMIN_MEDI',
    'YEARS_BUILD_AVG',
    'YEARS_BUILD_MODE',
    'YEARS_BUILD_MEDI'
]

df = df.drop(columns=cols_to_drop)

print(df.shape)

(307507, 106)

In [11]:
df["CREDIT_INCOME_RATIO"] = (
    df["AMT_CREDIT"] /
    df["AMT_INCOME_TOTAL"]
)

df["ANNUITY_INCOME_RATIO"] = (
    df["AMT_ANNUITY"] /
    df["AMT_INCOME_TOTAL"]
)

df["AGE_YEARS"] = (
    -df["DAYS_BIRTH"] / 365
)

df["EMPLOYMENT_YEARS"] = (
    -df["DAYS_EMPLOYED"] / 365
)

df["EMPLOYMENT_AGE_RATIO"] = (
    df["EMPLOYMENT_YEARS"] /
    df["AGE_YEARS"]
)

new_features = [
    "CREDIT_INCOME_RATIO",
    "ANNUITY_INCOME_RATIO",
    "AGE_YEARS",
    "EMPLOYMENT_YEARS",
    "EMPLOYMENT_AGE_RATIO"
]

df[new_features].describe()

,CREDIT_INCOME_RATIO,ANNUITY_INCOME_RATIO,AGE_YEARS,EMPLOYMENT_YEARS,EMPLOYMENT_AGE_RATIO
count,307507.000000,307495.000000,307507.000000,252133.000000,252133.000000
mean,3.957593,0.180931,43.937061,6.531897,0.156860
std,2.689737,0.094574,11.956116,6.406377,0.133548
min,0.004808,0.000224,20.517808,-0.000000,-0.000000
25%,2.018667,0.114783,34.008219,2.101370,0.056098
50%,3.265067,0.162833,43.150685,4.515068,0.118733
75%,5.159909,0.229067,53.923288,8.698630,0.219167
max,84.736842,1.875965,69.120548,49.073973,0.728811

In [13]:
df.to_csv(
    "C:\\Users\\Asus\\OneDrive\\Desktop\\Explainable-Credit-Risk-System\\data\\processed\\preprocessed_v1.csv",
    index=False
)

In [14]:
# Numerical columns
num_cols = df.select_dtypes(
    include=["int64", "float64"]
).columns

# Categorical columns
cat_cols = df.select_dtypes(
    include=["object"]
).columns

print("Numerical:", len(num_cols))
print("Categorical:", len(cat_cols))

Numerical: 96
Categorical: 15

C:\Users\Asus\AppData\Local\Temp\ipykernel_25512\1741216328.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(

In [15]:
num_missing = (
    df[num_cols]
    .isnull()
    .sum()
    .sort_values(ascending=False)
)

num_missing[num_missing > 0].head(20)

OWN_CAR_AGE           202927
LANDAREA_MEDI         182588
LANDAREA_MODE         182588
LANDAREA_AVG          182588
BASEMENTAREA_MODE     179942
BASEMENTAREA_MEDI     179942
BASEMENTAREA_AVG      179942
EXT_SOURCE_1          173376
NONLIVINGAREA_MEDI    169680
NONLIVINGAREA_AVG     169680
NONLIVINGAREA_MODE    169680
ELEVATORS_MODE        163890
ELEVATORS_MEDI        163890
ELEVATORS_AVG         163890
APARTMENTS_AVG        156060
APARTMENTS_MODE       156060
APARTMENTS_MEDI       156060
ENTRANCES_MODE        154827
ENTRANCES_AVG         154827
ENTRANCES_MEDI        154827
dtype: int64

In [16]:
cat_missing = (
    df[cat_cols]
    .isnull()
    .sum()
    .sort_values(ascending=False)
)

cat_missing[cat_missing > 0]

WALLSMATERIAL_MODE     156340
HOUSETYPE_MODE         154296
EMERGENCYSTATE_MODE    145754
OCCUPATION_TYPE         96389
NAME_TYPE_SUITE          1292
dtype: int64

In [18]:
extra_drop_cols = [
    "WALLSMATERIAL_MODE",
    "HOUSETYPE_MODE",
    "EMERGENCYSTATE_MODE"
]

df = df.drop(columns=extra_drop_cols)

In [ ]:
num_cols = df.select_dtypes(
    include=["int64", "float64"]
).columns

for col in num_cols:
    df[col] = df[col].fillna(
        df[col].median()
    )

In [23]:
df["OCCUPATION_TYPE"] = (
    df["OCCUPATION_TYPE"]
    .fillna("Unknown")
)

df["NAME_TYPE_SUITE"] = (
    df["NAME_TYPE_SUITE"]
    .fillna("Unknown")
)

In [24]:
df.isnull().sum().sum()

np.int64(0)

In [25]:
df.to_csv(
    "C:\\Users\\Asus\\OneDrive\\Desktop\\Explainable-Credit-Risk-System\\data\\processed\\preprocessed_v1.csv",
    index=False
)

In [26]:
cat_cols = df.select_dtypes(
    include=["object", "string"]
).columns

print(len(cat_cols))
print(cat_cols.tolist())

12
['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE']

In [27]:
for col in cat_cols:
    print(f"{col}: {df[col].nunique()}")

NAME_CONTRACT_TYPE: 2
CODE_GENDER: 2
FLAG_OWN_CAR: 2
FLAG_OWN_REALTY: 2
NAME_TYPE_SUITE: 8
NAME_INCOME_TYPE: 8
NAME_EDUCATION_TYPE: 5
NAME_FAMILY_STATUS: 6
NAME_HOUSING_TYPE: 6
OCCUPATION_TYPE: 19
WEEKDAY_APPR_PROCESS_START: 7
ORGANIZATION_TYPE: 58

In [28]:
df_encoded = pd.get_dummies(
    df,
    columns=cat_cols,
    drop_first=True,
    dtype=int
)

print(df_encoded.shape)

(307507, 209)

In [29]:
df_encoded.head()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,ORGANIZATION_TYPE_Trade: type 4,ORGANIZATION_TYPE_Trade: type 5,ORGANIZATION_TYPE_Trade: type 6,ORGANIZATION_TYPE_Trade: type 7,ORGANIZATION_TYPE_Transport: type 1,ORGANIZATION_TYPE_Transport: type 2,ORGANIZATION_TYPE_Transport: type 3,ORGANIZATION_TYPE_Transport: type 4,ORGANIZATION_TYPE_University,ORGANIZATION_TYPE_XNA
0,100002,1,0,202500.0,406597.5,24700.5,351000.0,0.018801,-9461,-637.0,...,0,0,0,0,0,0,0,0,0,0
1,100003,0,0,270000.0,1293502.5,35698.5,1129500.0,0.003541,-16765,-1188.0,...,0,0,0,0,0,0,0,0,0,0
2,100004,0,0,67500.0,135000.0,6750.0,135000.0,0.010032,-19046,-225.0,...,0,0,0,0,0,0,0,0,0,0
3,100006,0,0,135000.0,312682.5,29686.5,297000.0,0.008019,-19005,-3039.0,...,0,0,0,0,0,0,0,0,0,0
4,100007,0,0,121500.0,513000.0,21865.5,513000.0,0.028663,-19932,-3038.0,...,0,0,0,0,0,0,0,0,0,0

In [30]:
df_encoded.info()

<class 'pandas.DataFrame'>
Index: 307507 entries, 0 to 307510
Columns: 209 entries, SK_ID_CURR to ORGANIZATION_TYPE_XNA
dtypes: float64(56), int64(153)
memory usage: 492.7 MB

In [32]:
df_encoded.to_csv(
    "C:\\Users\\Asus\\OneDrive\\Desktop\\Explainable-Credit-Risk-System\\data\\processed\\preprocessed_v2_encoded.csv",
    index=False
)

In [33]:
X = df_encoded.drop(
    columns=["TARGET"]
)

y = df_encoded["TARGET"]

print(X.shape)
print(y.shape)

(307507, 208)
(307507,)

In [34]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(246005, 208)
(61502, 208)

In [35]:
print(y_train.value_counts(normalize=True) * 100)
print()
print(y_test.value_counts(normalize=True) * 100)

TARGET
0    91.926993
1     8.073007
Name: proportion, dtype: float64

TARGET
0    91.927092
1     8.072908
Name: proportion, dtype: float64

In [37]:
from imblearn.over_sampling import SMOTE

X = df_encoded.drop(columns=["TARGET"])
y = df_encoded["TARGET"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

print(y_train.value_counts(normalize=True) * 100)
print(y_test.value_counts(normalize=True) * 100)

(246005, 208)
(61502, 208)
TARGET
0    91.926993
1     8.073007
Name: proportion, dtype: float64
TARGET
0    91.927092
1     8.072908
Name: proportion, dtype: float64

In [38]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(
    random_state=42
)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train,
    y_train
)

print(X_train_smote.shape)
print(y_train_smote.shape)

(452290, 208)
(452290,)

In [39]:
y_train_smote.value_counts()

TARGET
0    226145
1    226145
Name: count, dtype: int64

In [40]:
y_train_smote.value_counts(normalize=True) * 100

TARGET
0    50.0
1    50.0
Name: proportion, dtype: float64

In [41]:
import joblib

joblib.dump(
    X_train_smote,
    "C:\\Users\\Asus\\OneDrive\\Desktop\\Explainable-Credit-Risk-System\\data\\processed\\X_train_smote.pkl"
)

joblib.dump(
    y_train_smote,
    "C:\\Users\\Asus\\OneDrive\\Desktop\\Explainable-Credit-Risk-System\\data\\processed\\y_train_smote.pkl"
)

['C:\\Users\\Asus\\OneDrive\\Desktop\\Explainable-Credit-Risk-System\\data\\processed\\y_train_smote.pkl']

In [42]:
X_train_smote.shape
y_train_smote.value_counts()
y_train_smote.value_counts(normalize=True) * 100

TARGET
0    50.0
1    50.0
Name: proportion, dtype: float64

In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score
)

lr = LogisticRegression(
    max_iter=1000,
    random_state=42
)

lr.fit(
    X_train_smote,
    y_train_smote
)

c:\Users\Asus\OneDrive\Desktop\Explainable-Credit-Risk-System\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000, random_state=42)

In [45]:
y_pred = lr.predict(X_test)

y_prob = lr.predict_proba(X_test)[:, 1]

In [46]:
print(classification_report(
    y_test,
    y_pred
))

              precision    recall  f1-score   support

           0       0.94      0.64      0.76     56537
           1       0.12      0.55      0.19      4965

    accuracy                           0.63     61502
   macro avg       0.53      0.60      0.48     61502
weighted avg       0.88      0.63      0.72     61502

In [47]:
print(confusion_matrix(
    y_test,
    y_pred
))

[[36162 20375]
 [ 2229  2736]]

In [48]:
print(
    "ROC-AUC:",
    roc_auc_score(y_test, y_prob)
)

ROC-AUC: 0.6274168182352791

In [49]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42,
    n_jobs=-1
)

rf.fit(
    X_train_smote,
    y_train_smote
)

RandomForestClassifier(max_depth=10, n_estimators=200, n_jobs=-1,
                       random_state=42)

In [50]:
y_pred_rf = rf.predict(X_test)

y_prob_rf = rf.predict_proba(X_test)[:, 1]

In [56]:
print(classification_report(
    y_test,
    y_pred_rf
))

print(confusion_matrix(
    y_test,
    y_pred_rf
))

print(
    "ROC-AUC:",
    roc_auc_score(y_test, y_prob_rf)
)

              precision    recall  f1-score   support

           0       0.92      0.95      0.94     56537
           1       0.17      0.12      0.14      4965

    accuracy                           0.88     61502
   macro avg       0.55      0.53      0.54     61502
weighted avg       0.86      0.88      0.87     61502

[[53656  2881]
 [ 4382   583]]
ROC-AUC: 0.6508269883097169

In [57]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="auc",
    random_state=42,
    n_jobs=-1
)

xgb.fit(
    X_train_smote,
    y_train_smote
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='auc', feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=-1, num_parallel_tree=None, ...)

In [58]:
y_pred_xgb = xgb.predict(X_test)

y_prob_xgb = xgb.predict_proba(X_test)[:, 1]

In [59]:
print(classification_report(
    y_test,
    y_pred_xgb
))

print(confusion_matrix(
    y_test,
    y_pred_xgb
))

print(
    "ROC-AUC:",
    roc_auc_score(y_test, y_prob_xgb)
)

              precision    recall  f1-score   support

           0       0.92      1.00      0.96     56537
           1       0.43      0.03      0.05      4965

    accuracy                           0.92     61502
   macro avg       0.68      0.51      0.51     61502
weighted avg       0.88      0.92      0.88     61502

[[56354   183]
 [ 4825   140]]
ROC-AUC: 0.7315819167588404

In [60]:
y_prob_xgb[:20]

y_prob_xgb.min(), y_prob_xgb.max()

(np.float32(0.0015053191), np.float32(0.81438375))

In [61]:
from sklearn.metrics import classification_report, confusion_matrix

for threshold in [0.5, 0.4, 0.3, 0.2]:
    y_pred_thresh = (y_prob_xgb >= threshold).astype(int)

    print(f"\nThreshold = {threshold}")
    print(classification_report(y_test, y_pred_thresh))

Threshold = 0.5
              precision    recall  f1-score   support

           0       0.92      1.00      0.96     56537
           1       0.43      0.03      0.05      4965

    accuracy                           0.92     61502
   macro avg       0.68      0.51      0.51     61502
weighted avg       0.88      0.92      0.88     61502


Threshold = 0.4
              precision    recall  f1-score   support

           0       0.92      0.99      0.96     56537
           1       0.35      0.07      0.11      4965

    accuracy                           0.91     61502
   macro avg       0.64      0.53      0.53     61502
weighted avg       0.88      0.91      0.89     61502


Threshold = 0.3
              precision    recall  f1-score   support

           0       0.93      0.97      0.95     56537
           1       0.29      0.15      0.19      4965

    accuracy                           0.90     61502
   macro avg       0.61      0.56      0.57     61502
weighted avg       0.88      0.90      0.89     61502


Threshold = 0.2
              precision    recall  f1-score   support

           0       0.94      0.91      0.92     56537
           1       0.23      0.31      0.27      4965

    accuracy                           0.86     61502
   macro avg       0.58      0.61      0.59     61502
weighted avg       0.88      0.86      0.87     61502

Threshold tuning was performed on the XGBoost model to improve detection of default cases. While the default threshold of 0.5 produced high precision, it identified only 3% of defaulters. Reducing the threshold to 0.2 increased recall to 31%, enabling the model to identify substantially more high-risk borrowers while maintaining acceptable precision. Since the cost of missing a defaulter is typically higher than incorrectly flagging a low-risk borrower, a threshold of 0.2 was selected for risk assessment.

In [62]:
import pandas as pd

df_encoded = pd.read_csv(
    "C:\\Users\\Asus\\OneDrive\\Desktop\\Explainable-Credit-Risk-System\\data\\processed\\preprocessed_v2_encoded.csv"
)

print(df_encoded.shape)

(307507, 209)